services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/criar_banco.sql:/docker-entrypoint-initdb.d/criar_banco.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - backend


  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    networks:
      - backend


  superset:
    image: apache/superset:4.0.2
    container_name: superset
    restart: unless-stopped
    ports:
      - "${SUPERSET_PORT}:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - superset_home:/app/superset_home
      - ./dashboard:/app/dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username $${SUPERSET_ADMIN_USERNAME} --firstname Admin --lastname Dev --email admin@ficdev.local --password $${SUPERSET_ADMIN_PASSWORD} || true &&
        superset init &&
        python /app/dashboard/sync_database.py || true &&
        /usr/bin/run-server.sh
      "


volumes:
  postgres_data:
  mongo_data:
  superset_home:


networks:
  backend:
    driver: bridge